### ISSUE TITLE
Application cleanup for inventory singleton

### ISSUE THREAD

**Issue by damb** [SeisComP/common#11]
Hi devs,

while implementing unittests for a concrete implementation of `Seiscomp::Client::StreamApplication` I run into the issue that the `inventory_` member of the `Seiscomp::Client::Inventory` singleton instance i.e. https://github.com/SeisComP/common/blob/ecfeba10d3bf961d8ac426aeedf1a8dc07e453fd/libs/seiscomp/client/inventory.h#L146 is not properly reset during application cleanup. Of course, I could add something like
```C++
void MyApplication::done() {
   ...
   Seiscomp::Client::Inventory::Instance()->setInventory(nullptr);
}
```
which would do the job. However, IMO it would be cleaner to add this line to https://github.com/SeisComP/common/blob/ecfeba10d3bf961d8ac426aeedf1a8dc07e453fd/libs/seiscomp/client/application.h#L465 since `Seiscomp::Client::Application` handles the `Seiscomp::Client::Inventory`, anyway.

What do you think?

EDIT: Correct namespace

**Comment by gempa-jabe** [comment]
That sounds reasonable. Actually since Inventory is a global instance (outside of Application scope) it is also arguable if the application should clean up the state of this global instance. The application loads the global inventory based on some rules but that's it. I don't know of any implementation which uses the inventory after the application has been destroyed so adding that cleanup is OK.

**Comment by gempa-jabe** [comment]
See 04050c85931b2c6c4b798f05c60f21051c226954.

**Comment by gempa-jabe** [comment]
Please let me know if that fixes your tests.

**Comment by damb** [comment]
Thanks, @gempa-jabe. The fix does its job and works correctly.
