### ISSUE TITLE
Allow NonLinLoc grids to be used as travel time tables by SeisComP modules

### ISSUE THREAD

**Issue by luca-s** [SeisComP/common#23]
Dear developers,

this is a proposal that requires some work on your side, so if there is no interest please feel free to close the issue. 

I wrote [some code](https://github.com/swiss-seismological-service/scrtdd/blob/master/libs/hdd/nllttt.h)  that reads NonLinLoc grid files and I use them as travel time tables. I initially wanted to register the code as a plugin that implements the  [TravelTimeTableInterface](https://github.com/SeisComP/common/blob/02c0e2854199ac64bdd5ed862306be4d9a637bfa/libs/seiscomp/seismology/ttt.h#L101), which would allow to use the grids with any module, especially scolv. This is interesting because that would enable 3D velocity models in SeisComP. Unfortunately that is not possible because the current interface is not suitable for NonLinLoc grids (or the grids are not suitable for SeisComP):

- the current interface computes travel times between any [two locations](https://github.com/SeisComP/common/blob/02c0e2854199ac64bdd5ed862306be4d9a637bfa/libs/seiscomp/seismology/ttt.h#L135) while NonLinLoc grids work between any point and a specific station
- NonLinLoc computes only P and S and not all the phase types available with Locsat and libtau

In case you are interested in following up the idea please let me know.

**Comment by gempa-jabe** [comment]
That is indeed interesting for NLL users, I think.

> the current interface computes travel times between any two locations while NonLinLoc grids work between any point and a specific station

One option to make that work with the current interface is to build a lookup table for locations (lat/lon) -> station and search the grid based on that table lookup and the input coordinates.

Otherwise the interface must be changed to take an arbitrary receiver code (N.S.L) in addition to the locations. Just passing the receiver code is not enough as most implementations require the coordinates of the receivers from somewhere. Passing both might lead to inconsistencies if coordinates and code do not match. The implementation cannot check that. If it could check that then you don't need to pass the code as you are able to look it up from the coordinates. Changing the interface always requires many places to be changed as well including Python code (which is the real pain). Wouldn't a lookup table working for you? Any concerns using it?

> NonLinLoc computes only P and S and not all the phase types available with Locsat and libtau

The number of phases is not important for the interface. You just return what is available.

**Comment by luca-s** [comment]
Sure, that's a possible workaround. However the  TravelTimeTableInterface is already outdated because it was written for libtau: Locasat implementatin returns mostly empty fields. So I thought to double check with you if you have plans already to update the interface before deciding to implement a workaround. Thanks!

**Comment by gempa-jabe** [comment]
Actually the interface should return the superset of values that are returned by any travel time table. To not set values is fine, throwing computed values away is less desirable.

**Comment by luca-s** [comment]
Yes, that's one way to look at that but it might be also true the exact opposite: write API that returns only what it can be provided by all implementations, so that robust and straightfoward code can be built on top of it.

As a side note, it is very strange that the current interface doesn't return the velocity at source, which is the basic information provided by a velocity model.

**Comment by jsaul** [comment]
Note that travel time tables in general don't "know" the velocity at the source.

What you have in mind is essentially a subset of a more general "give me the velocities at any point in the model". Which would be a useful interface but also complicate things.

**Comment by luca-s** [comment]
I agree, that would not be easy. Actually, nothing of what I proposed is easy. The point of opening this issue was to double check if there was already the idea on your side of updating the TravelTimeTableInterface. In that was the case I wanted to throw my 2 cents in the mix. For now I can leave with the workaround proposed by @gempa-jabe
