### ISSUE TITLE
Create `GenericRecord` from `Record`

### ISSUE THREAD

**Issue by damb** [SeisComP/common#38]
Hi devs,

there is the following constructor which allows creating a `GenericRecord` from a `Record` https://github.com/SeisComP/common/blob/c0d41e7b29e378a0cff624508dcd6fdbda6b5dd2/libs/seiscomp/core/genericrecord.h#L58-L59 with the definition https://github.com/SeisComP/common/blob/c0d41e7b29e378a0cff624508dcd6fdbda6b5dd2/libs/seiscomp/core/genericrecord.cpp#L67
Is there a reason why the `rec`'s data is not copied (`Record` declares an abstract method which must be implemented by concrete implementations, anyway)?: https://github.com/SeisComP/common/blob/c0d41e7b29e378a0cff624508dcd6fdbda6b5dd2/libs/seiscomp/core/record.h#L186-L188

**Comment by gempa-jabe** [comment]
Data is not copied because the method returns a const array and `GenericRecord` owns the array and would need to case away constness or copy the data anyway. Copying the data must be done by the caller where it can be converted to the desired datatype. Usually we use this `GenericRecord` conversion from `MSeedRecord` which carries an integer array and must be converted to float or double anyway. So the data copy in the constructor would be a waste.

**Comment by damb** [comment]
Thanks for the clarification. This makes absolutely sense.
