### ISSUE TITLE
Handling of nan in xml files

### ISSUE THREAD

**Issue by luca-s** [SeisComP/common#64]
Dear developers,

I have noticed that `scdb` is not able to import events that contain nan values. That might be the expected behaviour and I am fine with that, but I wanted to report this particular case just to be sure is not a bug.

What happened is that I processed some data in playback (`scautopick`, `scanloc`, `screloc`, `scevent`) using the `--ep` option. Due to a misconfiguration of NonLinLoc, its XML output was lacking the lat/lon/depth uncertainty. An example of the output follows:

```
<latitude>
  <value>46.51048231</value>
  <uncertainty>-nan</uncertainty>
</latitude>
<longitude>
  <value>8.476244074</value>
  <uncertainty>-nan</uncertainty>
</longitude>
<depth>
  <value>-1.4119125</value>
  <uncertainty>-nan</uncertainty>
</depth>
```

I initially didn't notice the nan values and I imported the output with `scdb`, but I couldn't see the events in the database, only the picks. Then I realized the problem with nans.

I wonder what is the most suitable behaviour that SeisComP should have. Should the nan not being exported in the first place? Should the nan be read and imported in the db? Is the current behaviour already fine? What do you think?

thanks
Luca

**Comment by gempa-jabe** [comment]
See https://dev.mysql.com/doc/refman/5.7/en/type-conversion.html. MYSQL does not support that and states that the SQL standard does not allow NaN, +/-INF as valid values. So ignoring objects with invalid values is correct.

When it comes to exporting NaN values to e.g. XML then it gets more tricky. C++ allows it, it is a valid expression of a float or double value. The decision we made was to allow to export what is possible for a concrete archive implementation. Otherwise we would have to come up with a standard that will serve all possible implementations and that is not possible. Just imagine we implement an archive that only allows strings with a maximum length of 255 (e.g. remember Turbo Pascal?) then we would need to add that restriction to any archive. Not a good idea in my opinion. Furthermore archive implementations can be added by users so we just don't know what a user will ever implement.

To avoid issues with doubles and floats we would have to add a check to each setter, check for invalid values and throw an exception. It would slow down things slightly but with the benefit of increased consistency. But if you manipulate the memory of an object directly you could still set invalid values and bypass any checks (not the normal use case but possible). That convinces me that handling errors in the archive is the most flexible and the most simple solution.

Increasing the user experience of e.g. scdb to warn about those issues is welcome. Then you would know that something has screwed up. But that is another topic.

**Comment by luca-s** [comment]
I agree with all you said. I don't even think `scdb` needs a better user experience; it properly states the number of errors it encountered while writing to the database and with the `--debug` option the errors are clearly printed and understandable.

Thanks for the discussion.
