### ISSUE TITLE
[GUI] picker/amplitude views show wrong theoretical arrivals when origin has negative depth

### ISSUE THREAD

**Issue by luca-s** [SeisComP/common#66]
The theoretical arrivals on the picker and amplitude GUIs are not properly computed when an origin has a negative depth. This is because the negative depth is set to +1km when calling the travel time table implementations . See [here](https://github.com/SeisComP/common/blob/4a85104ea1fe99cc8ce1ef012909d20ad3d2f8a5/libs/seiscomp/gui/datamodel/amplitudeview.cpp#L4274) and [here](https://github.com/SeisComP/common/blob/4a85104ea1fe99cc8ce1ef012909d20ad3d2f8a5/libs/seiscomp/gui/datamodel/pickerview.cpp#L4899).

While I understand the "safety belt" intentions behind this choice, it would be much better to add the depth check in the travel time table implementation themselves. That would allow other TTT implementations that handle negative depths to work properly.

What do you think?

Thanks,
Luca

**Comment by jsaul** [comment]
I don't remember the rationale of this 1-km setting. It may be related 
to some numerical issues related to exact-zero depth, which however 
could be fixed by setting the depth to just 1 meter (not kilometer). 
That was long ago.

But I agree with what you say. The current tables are not correct for 
extremely shallow or negative depths and therefore need to be fixed.

**Comment by luca-s** [comment]
So my idea would be to remove the two lines mentioned above and add some depth constraints in the travel time table implementations. `libtau` has [already a check](https://github.com/SeisComP/common/blob/968d7d13c0ed3d51311159dcafdc5da06ed26ee4/libs/seiscomp/seismology/ttt/libtau.cpp#L133) for that , so I could add a check to LOCSAT ttt too.

**Comment by gempa-jabe** [comment]
Yes, that makes much more sense to me.
