### ISSUE TITLE
Proposal to add a local seismicity locator

### ISSUE THREAD

**Issue by luca-s** [SeisComP/common#83]
Dear developers,

I have been working on a couple of projects where they need a locator for very local seismicity (few kms and few hundreds of meters).  In this scenario I cannot use the default SeisComP locators because they do not take into consideration station elevations, negative source depths  and neither their  travel time table models do.

 We also use borehole sensors , which means the locator has to take into consideration that the earthquakes can happen also above the sensors. Basically many assumptions valid for regional seismicity break at this small scales. 

The only locator that works pretty well is NonLinLoc, but to achieve a good location resolution the number of iterations for the Octtree method has to be set  so high that it doesn't fit well for real-time applications, especially if you intend to use NonLinLoc within scanloc.

So I wrote [this simple locator ](https://github.com/swiss-seismological-service/genloc), which is the perfect complement to the `homogeneous` travel time table.

I wonder if you are interested in merging this code into SeisComP, since I don't get anything from keeping it in a separate repository. In case you are interested, just let me know and I will provide a PR where we can discuss improvements and changes required for the integration.

best
Luca

**Comment by gempa-jabe** [comment]
That sounds great @luca-s. Not that I have tested your locator but I am pretty confident that something that complements your homogeneous travel time tables and serves as an additional locator options is a great and valuable addition. And the fact that your are still active with development so that bugs and issues are going to be fixed makes this integration very tempting. I have no issues accepting a PR. I only have to check formatting of the source ;).

Btw, as more algorithms require standard code such as fitting methods or statistical methods it would be great to put them all into one place and homogenize them. I know that this is not gonna be fun but the `3rd-party` directories are kind of hidden and other code won't be able to re-use it, especially in a plugin.

**Comment by luca-s** [comment]
Good, then I will provide the PR where we can discuss changes in more details. I am pretty sure there are user level configuration that you might want to modify, clarify and what not.  

Should I follow the homogeneous approach where I put GenLoc code in a anonymous namespace to avoid polluting the SeisComP one?

**Comment by luca-s** [comment]
We can move the discussion here #84
